<?php $this->extend('base.phtml') ?>
<?php $this->block('content') ?>
<h1><?=$this->article['title'] ?></h1>
    <p>
        <?= $this->article['text'] ?>
    </p>
    <?= (new Template())->render(
            'components/comments-block.phtml',
            [
                'articleId' => $this->article['id'],
                'comments' => $this->comments
            ]);
    ?>
<?php $this->endblock() ?>