<?php $this->extend('base.phtml') ?>
<?php $this->block('content') ?>
    <h1 style="display: flex; justify-content: space-between;">
        <?= trans('Articles') ?>
        <?= isset($_SESSION['user_id']) && isAdmin($_SESSION['user_id'])
            ? '<a href="/article/create" style="text-align: right">+</a>'
            : '' ?>
    </h1>

<ul>
    <?php foreach ($this->articles as $article): ?>
        <li>
            <a href="/article/<?=$article['id']?>"><?=$article['title'] ?></a>
            <span style="color: dimgray"><?=$article['created_at'] ?></span>
            <?= $this->isAdmin ? '<a href="/article/'.$article['id'].'/edit">(edit)</a>' : '' ?>
        </li>
    <?php endforeach; ?>
</ul>


<?php $this->endblock() ?>