<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="theme-color" content="#1214b0">
    <link rel="stylesheet" type="text/css" href="/style.css">
    <?= $this->stylesheets ?>
    <title>L.A. Personal page</title>
</head>
<body>
<audio id="myAudio" autoplay src="/beep.mp3" type="audio/mp3"></audio>
<header>
    <div class="title gradient-box">
        <?=trans('personal_web_page') ?>
    </div>
    <div class="tabs">
        <ul>
            <a href="/"><li class="<?= '/' === $this->path ? 'active' : '' ?>"><?=trans('Main') ?></li></a>
            <a href="/articles"><li class="<?= '/articles' === $this->path ? 'active' : '' ?>"><?=trans('Articles') ?></li></a>
            <a href="/contact"><li class="<?= '/contact' === $this->path ? 'active' : '' ?>"><?=trans('Contact') ?></li></a>
        </ul>
        <div class="user-info">
            <?php if (isset($_SESSION['login'])) {
                // TODO логин плохо отображается на мобилах, надо вынести на новую строчку
                echo(!$_SESSION['login'].': '.'<a href="/logout">'.trans('Logout').'</a>');
            } else {
                echo('<a href="/login">'.trans('Login').'</a>');
            } ?>
        </div>
    </div>
</header>
<div class="container">
    <div class="in-block">
        <div class="left content">
            <?= flash('login') ?>
            <?= flash('registration') ?>
            <?= $this->content ?>
        </div>
        <div class="divider"></div>
        <div class="right content">
            <fieldset>
                <legend>Language:</legend>
                <?= (new Template())->render(
                        'components/switch.phtml',
                        [
                            'field' => 'lang',
                            'options' => array_map(function ($case) { return $case->value; }, Language::cases()),
                            'default' => Language::ENGLISH->value
                        ]
                ) ?>
            </fieldset>
        </div>
    </div>
</div>
<footer class="gradient-box">
    <div class="content">
        <?=trans('all_rights_reserved') ?>
    </div>
</footer>
<?= $this->modal ?>
</body>
</html>