<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="/style.css">
    <title>L.A. Personal page</title>
</head>
<body>
<header>
    <div class="title gradient-box">
        Leonid Averianov personal web page
    </div>
    <div class="tabs">
        <ul>
            <a href="/"><li class="<?= '/' === $this->path ? 'active' : '' ?>">Main</li></a>
            <a href="/articles"><li class="<?= '/articles' === $this->path ? 'active' : '' ?>">Articles</li></a>
            <a href="/contact"><li class="<?= '/contact' === $this->path ? 'active' : '' ?>">Contact</li></a>
        </ul>
        <div class="user-info">
            <?php if (isset($_SESSION['login'])) {
                echo($_SESSION['login'].': '.'<a href="/logout">Logout</a>');
            } else {
                echo('<a href="/login">Login</a>');
            } ?>
        </div>
    </div>
</header>
<main>
    <div class="in-block">
        <div class="left content">
            <?= $this->content ?>
        </div>
        <div class="divider"></div>
        <div class="right content">
            <fieldset>
                <legend>Language:</legend>
                <?= (new Template())->render(
                        'components/switch.phtml',
                        [
                            'field' => 'lang',
                            'options' => ['English', 'Русский'],
                            'default' => 'English'
                        ]
                ) ?>
            </fieldset>

            <fieldset>
                <legend>Font:</legend>
                <div class="select-options">
                    <a class="active">►&#0020;Pixelated</a>
                    <a>&#0020;&#0020;Sans</a>
                </div>
            </fieldset>
        </div>
    </div>
</main>
<footer class="gradient-box">
    <div class="content">
        All rights reserved. Made with PHP without any javascript and fancy frameworks.
    </div>
</footer>
<?= $this->modal ?>
</body>
</html>